### ISSUE TITLE
Preference Handler - deletePrefence

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-server#13]
Might be useful to have a function

<pre>
deletePreference(application_string,key_string)
</pre>

and/or a
<pre>
deletePreferences(application_string)
</pre>

**Comment by oarchner** [comment]
A prefence can already be deleled by setting its value to null:
```
cli.execute("PreferenceHandler.setPreference","MyApplication","MyKey",null )
````

**Comment by oarchner** [comment]
Added function:
```
 cli.execute("PreferenceHandler.deletePreferences","MyApplication")
```
See [TestPreferenceHandler.java](https://github.com/BayCEER/bayeos-server/blob/master/src/test/java/de/unibayreuth/bayceer/bayeos/xmlprc/handler/TestPreferenceHandler.java)
