### ISSUE TITLE
Automatically enable aggregation and history deletion with debian package

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-server#15]
To enable aggregation the bayeos-server admin still has to do some manuall configuration and add a crontab like this one:

<pre>
0 * * * * (psql -U bayeos -d bayeos -c 'select aggr_calculate();' > /dev/null)
1 1 3 * * (psql -d bayeos -c 'SET search_path TO bayeos; select arch_his();' > /dev/null)
</pre>

*Suggestion:*
Add a bayeos-crontab file to /etc/cron.d/ like the php5 package:
<pre>
# /etc/cron.d/php5: crontab fragment for php5
#  This purges session files older than X, where X is defined in seconds
#  as the largest value of session.gc_maxlifetime from all your php.ini
#  files, or 24 minutes if not defined.  See /usr/lib/php5/maxlifetime

# Look for and purge old sessions every 30 minutes
09,39 *     * * *     root   [ -x /usr/lib/php5/maxlifetime ] && [ -x /usr/lib/php5/sessionclean ] && [ -d /var/lib/php5 ] && /usr/lib/php5/sessionclean /var/lib/php5 $(/usr/lib/php5/maxlifetime)

</pre>
 
arch_his() should preferable just truncate the history tables.

**Comment by oarchner** [comment]
New cron file `/etc/cron.d/bayeos` with calls to SQL function `aggr_calculate()` and `shrink_his_massendaten()` as user bayeos.
