### ISSUE TITLE
ToolsHandler.changePassword does not validate old password and ACL

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-server#7]
ToolsHandler.changePassword changes password without checking write access to user object and independently whether the old password sent by XML-RPC is correct.

Both checks should be performed before calling the update statement.

The fix should set full access to all users per default.

**Comment by oarchner** [comment]
+ Added permission check in ToolsHandler.changePassword()
+ Added password verification in ToolsHandler.changePassword()
+ Created permission for all users
