### ISSUE TITLE
No pre aggregation for series with resolution equal 3600?

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-server#9]
I have some time series in my BayEOS database with resolution 3600. Non has a pre aggregated series (day, month, year). Other series with resolution 86400 have aggregated series (month, year).

**Comment by oarchner** [comment]
Verified this on the following series:
![series](https://cloud.githubusercontent.com/assets/5363999/8106478/f6df2e22-1041-11e5-8306-fdaa2c398bb1.jpg)


with the following data:
![data](https://cloud.githubusercontent.com/assets/5363999/8106443/b4ba30e6-1041-11e5-8d86-dd10658f86ae.jpg)

Result looks valid:
![result](https://cloud.githubusercontent.com/assets/5363999/8106454/ce9c01ec-1041-11e5-91ef-cf3accc60509.jpg)

Please check whether the resolution was set __before__ the aggregation was started.
